cmd_jmeter: bin\jmeter.bat
mailfrom:  noreply@brinks.fr
fromname: Supervision Site WEB (Dashboard)
websites:
  commandweb:
    url: .\security\commandweb.jmx
    mailto: DG.DSIAstreinte@brinks.fr
    toname: DG.DSI astreinte
  repository:
    url: .\security\repository.jmx
    mailto: DG.DSIAstreinte@brinks.fr
    toname: DG.DSI astreinte
