cmd_jmeter: bin\jmeter.bat
mailfrom:  noreply@brinks.fr
fromname: Supervision Dashboard
websites:
  commandweb:
    url: .\security\commandweb.jmx
    mailto: m.chauffour@brinks.fr
    toname: Marc Chauffour
  repository:
    url: .\security\repository.jmx
    mailto: m.chauffour@brinks.fr
    toname: Marc Chauffour
