cmd_jmeter: bin\jmeter.bat
mailfrom:  noreply@brinks.fr
fromname: Supervision Site WEB (Dashboard)
mailactive: "false"
websites:
  commandweb:
    url: .\security\commandweb.jmx
    no_mailto: m.chauffour@brinks.fr
    mailto: DG.DSIAstreinte@brinks.fr
    toname: DG.DSI astreinte
    mailactive: "true"
  repository:
    url: .\security\repository.jmx
    no_mailto: m.chauffour@brinks.fr
    mailto: DG.DSIAstreinte@brinks.fr
    toname: DG.DSI astreinte
    mailactive: "true"
databases:
  cash_srv:
    url: .\security\oradb-cash.jmx
    options: -l $output$ -Djmeter.save.saveservice.output_format=$format$
    output: output.csv
    format: csv
    mailactive: "false"
