version5:
    format: csv
    queries:
      withoutoffice:
        query: >
          (select (name)
          (except
          (from device)
          (from device
          (with package
          (where package (eq name (pattern *Microsoft*Office*)))))))
        values:
          name: count
          formula: 1
          agregate: count
      recent_updates:
        query: >
          (select (name #"*Entity" first_seen last_seen)
          (except
          (from device
          (with installation
          (between midnight midnight+1d)
          (compute number_of_packages)))
          (from device (where device (gt first_seen (datetime midnight-3d))))))
        values:
          - name: update_by_site
            formula: entity
            agregate: group_by
          - name: device_updated
            formula: 1
            agregate: count
          - name: updates
            formula: number_of_packages
            agregate: sum
          - name: max_updates
            formula: number_of_packages
            agregate: max
      alldrives:
        query: >
          (select
          (name distinguished_name total_drive_capacity total_drive_free_space total_drive_usage
          first_seen last_seen device_type total_ram number_of_days_since_last_boot last_logon_time
          group_name *entity)
          (from device (with connection (between now-15m now)))
        values:
          name: used_space
          formula: total_drive_capacity-total_drive_free_space
          agregate: sum
      extractionstd:
        query: >
          (select
          (name device_type group_name #"*Entity")
          (from device
          (with connection (between now-5m now)
          (where binary (eq executable_name (pattern global_agence5.exe))))))
        values:
          name: usage
          formula: 1
          agregate: count
      horusquality:
        query: >
          (select
          (name device_type group_name #"*Entity")
          (from device
          (with connection (between now-1h now)
          (where binary (eq executable_name (pattern kheops.horus.clients.windows.exe)))
          (compute incoming_traffic outgoing_traffic average_network_response_time successful_connections_ratio network_availability_level)
          )))
        values:
          - name: availability1
            formula: average_network_response_time
            agregate: min
          - name: availability2
            formula: average_network_response_time
            agregate: average
          - name: availability3
            formula: average_network_response_time
            agregate: max
          - name: count
            formula: name
            agregate: count
          - name: netavailability
            formula: network_availability_level
            agregate: group_by
      darwinquality:
        query: >
          (select
          (name device_type group_name #"*Entity")
          (from device
          (with connection (between now-1h now)
          (where binary (eq executable_name (pattern darwin.exe)))
          (compute incoming_traffic outgoing_traffic average_network_response_time successful_connections_ratio network_availability_level)
          )))
        values:
          - name: availability1
            formula: average_network_response_time
            agregate: min
          - name: availability2
            formula: average_network_response_time
            agregate: average
          - name: availability3
            formula: average_network_response_time
            agregate: max
          - name: count
            formula: name
            agregate: count
          - name: netavailability
            formula: network_availability_level
            agregate: group_by
      high_threat:
        query: >
          (select (name #"*Entity")
          (from device
          (with execution
          (where binary (eq threat_level (enum high)))
          (compute number_of_binaries)
          (between midnight-1d midnight)))
          (limit 100)
          (order_by name desc))
        values:
          - name: devices
            formula: 1
            agregate: count
          - name: max_threats
            formula: number_of_binaries
            agregate: max
          - name: device_list
            agregate: list
            formula: name,entity,number_of_binaries
      intermediate_threat:
        query: >
          (select name
          (from device
          (with execution
          (where binary (eq threat_level (enum intermediate)))
          (compute number_of_binaries)
          (between midnight-1d midnight)))
          (limit 100)
          (order_by name desc))
        values:
          - name: devices
            formula: 1
            agregate: count
          - name: max_threats
            formula: number_of_binaries
            agregate: max
      cash_availability:
        query: >
          (select
          (name #"Destination Type" #"Server location")
          (from destination
          (with connection (between now-1h now)
          (where destination
          (eq #"Destination Type"
          (enum Agence))
          (eq name
          (pattern sfr*))
          )
          (compute network_availability_level))
          (having (ne network_availability_level (enum high)
          )))
        values:
          - name: servers
            formula: network_availability_level
            agregate: group_by
          - name: sites
            formula: server_location,network_availability_level
            agregate: list
